#!/bin/bash

docker run -e SONAR_LOGIN=admin -e SONAR_PASSWORD=admin -e SONAR_PROJECT_BASE_DIR=local-config \
  --user="0:0" -it -v "$PWD:/usr/src" --rm --link sonarqube \
  sonarsource/sonar-scanner-cli
