#!/bin/bash

docker run -e SONAR_LOGIN=admin -e SONAR_PASSWORD=admin \
  --user="0:0" -it -v "$PWD:/usr/src" --rm --link sonarqube \
  --entrypoint=sonar-scanner sonarsource/sonar-scanner-cli \
  -Dproject.settings=sonar-project-local.properties
